apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-oss-120b-blackwell
  namespace: vllm
  labels:
    app: gpt-oss-120b-blackwell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-oss-120b-blackwell
  template:
    metadata:
      labels:
        app: gpt-oss-120b-blackwell
    spec:
      nodeName: gx10-e1bd
      runtimeClassName: nvidia 
      volumes:
      - name: cache-volume
        hostPath:
          path: /home/hyperscalers/Documents/models # Path to the local directory on the node
          type: DirectoryOrCreate
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      containers:
      - name: vllm
        image: peratchikannan/hs-public:vllm-spark-custom-v2
        command: ["/bin/sh", "-c"]
        runtimeClassName: nvidia
        args: [
          "NCCL_P2P_DISABLE=1 vllm serve qwen/qwen3-vl-30b-a3b-thinking --host 0.0.0.0 --port 8000 --tensor-parallel-size 1 --async-scheduling --tool-call-parser openai --api-key <your-api-key-goes-here> --served-model-name intrallmai/intrallm-120b"
        ]
        env:
        # - name: HUGGING_FACE_HUB_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: hf-token-secret
        #       key: token
        - name: NCCL_P2P_DISABLE
          value: "1"
        - name: VLLM_PORT
          value: "80"
        - name: "VLLM_LOGGING_LEVEL"
          value: "DEBUG"        
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        # - name: NVIDIA_DRIVER_CAPABILITIES
        #   value: "compute,utility"
        # - name: LD_LIBRARY_PATH
        #   value: "/usr/lib/aarch64-linux-gnu/:/usr/local/cuda/lib64:$(LD_LIBRARY_PATH)"
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "10"
            memory: 20G
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            memory: 6G
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
